import Header from "@/component/layout/Header/Header";
import Footer from "@/component/layout/Footer/Footer";

import type { Metadata } from "next";
import { avenir, manrope } from "@/lib/fonts/fonts";
import "../globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function OtherLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${manrope.variable} ${avenir.variable} h-full antialiased`}
        >
            <body className="flex min-h-full flex-col">
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
